---
new_page_extension: md
auto_deploy: false
admin_path: "/public/admin"
webhook_url: 
sections:
- type: directory
  path: _data/authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - authors
- type: directory
  path: _posts
  label: posts
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: ''
public_path: https://ys-storage-public-blogtech-content-bucket.s3.eu-west-3.amazonaws.com
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
