backend:
  name: github
  repo: Yousign/blog
  base_url: https://blog-git-admin.yousign.vercel.app
  auth_endpoint: api/auth
media_folder: public/assets
public_folder: img
collections:
  - label: "Post"
    name: "post"
    folder: "_posts"
    create: true
    identifier_field: title
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
